# -*- coding: utf-8 -*-
"""SUTT TASK1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRP4A1QYdcBDTqC45stf-mulq8RTXj21
"""

import pandas as pd

#Specify mess menu file path
FilePath = '/content/Mess Menu Sample.xlsx'

test = pd.read_excel(FilePath, skiprows = [ 12, 22], dtype=str)
test

#Saving Dates
dates = [str(date).split()[0] for date in test.iloc[0, :].tolist()]
dates

menu = {}

for i, date in enumerate(dates):
    if pd.isna(date):
        continue

    meal_ranges = [
        (2, 11, "BREAKFAST"),
        (12, 20, "LUNCH"),
        (21, None, "DINNER")
    ]

    date_menu = {
        "BREAKFAST": [],
        "LUNCH": [],
        "DINNER": []
    }

    for start, end, meal_type in meal_ranges:
        items = test.iloc[start:end, i].dropna().tolist()
        cleaned_items = [' '.join(item.upper().strip().split())
                        for item in items if "*" not in item]
        date_menu[meal_type] = cleaned_items

    menu[date] = date_menu

import json

json_output_path = "menu.json"
with open(json_output_path, "w", encoding="utf-8") as json_file:
    json.dump(menu, json_file, indent=4, ensure_ascii=False)

print(f"Menu successfully saved to {json_output_path}")

